// ── F4 Komplettes Marketing-Paket: Kanal-Generierung MIT Strategie-Kern ───────
// Each channel is generated by the EXISTING single-channel generator
// (src/ai/generate.ts → src/ai/providers/openai.ts) — prompts are NOT
// rewritten. The shared kernel is simply prepended to the request as
// "Gemeinsamer Strategie-Kern: …" additional context, so every channel
// naturally adopts the same keywords, hook, CTA and voice.
// F1 Qualitäts-Score is attached by the existing generateContent() pipeline.

import type { ContentRequest, ContentResult, ContentType } from '../types';
import type { MarketingKernel } from './kernel';

/** The five publishable channels of the package. */
export const PACKAGE_CHANNELS: Array<{ key: string; contentType: ContentType }> = [
  { key: 'pinterest', contentType: 'pinterest_pin' },
  { key: 'etsy', contentType: 'etsy_listing' },
  { key: 'seo', contentType: 'seo_blog' },
  { key: 'social', contentType: 'social_post' },
  { key: 'newsletter', contentType: 'email_newsletter' },
];

/** Build the "Gemeinsamer Strategie-Kern" context block prepended to every channel request. */
export function kernelContext(kernel: MarketingKernel): string {
  return `Gemeinsamer Strategie-Kern (für dieses Paket verbindlich — verwende diese Keywords, diese Hauptbotschaft, diesen CTA und diese Stimme in deinem Output):
- Keywords: ${kernel.keywords.join(', ')}
- Hauptbotschaft/Hook: ${kernel.mainHook}
- Call-to-Action: ${kernel.cta}
- Ton/Stimme: ${kernel.voice}
- Zielgruppe: ${kernel.audienceNote}`;
}

/**
 * Generate ONE package channel with the shared kernel + optional F6
 * Strategie-Brief as context. The result includes the F1 score (attached by
 * the existing pipeline). Without a brief the request is identical to F4.
 */
export async function generatePackageChannel(
  kernel: MarketingKernel,
  contentType: ContentType,
  productIdea: string,
  briefContext?: string,
): Promise<ContentResult> {
  const request: ContentRequest = {
    contentType,
    productIdea,
    additionalContext: [kernelContext(kernel), briefContext].filter(Boolean).join('\n\n'),
  };
  const { generateContent } = await import('../generate');
  return generateContent(request);
}
