/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppTiktokRouteImport } from './routes/app/tiktok'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppPricingRouteImport } from './routes/app/pricing'
import { Route as AppPerformanceRouteImport } from './routes/app/performance'
import { Route as AppPackageRouteImport } from './routes/app/package'
import { Route as AppNewProjectRouteImport } from './routes/app/new-project'
import { Route as AppImageStudioRouteImport } from './routes/app/image-studio'
import { Route as AppFeedbackRouteImport } from './routes/app/feedback'
import { Route as AppContentLibraryRouteImport } from './routes/app/content-library'
import { Route as AppCalendarRouteImport } from './routes/app/calendar'
import { Route as AppBrandRouteImport } from './routes/app/brand'
import { Route as AppBillingRouteImport } from './routes/app/billing'
import { Route as AppBetaWelcomeRouteImport } from './routes/app/beta-welcome'
import { Route as AppBetaSignupsRouteImport } from './routes/app/beta-signups'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppAdminTrackingRouteImport } from './routes/app/admin-tracking'
import { Route as AppSignUpIndexRouteImport } from './routes/app/sign-up/index'
import { Route as AppSignInIndexRouteImport } from './routes/app/sign-in/index'
import { Route as AppSignUpSplatRouteImport } from './routes/app/sign-up/$'
import { Route as AppSignInSplatRouteImport } from './routes/app/sign-in/$'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app/projects/$projectId'
import { Route as AppGeneratePinterestRouteImport } from './routes/app/generate/pinterest'
import { Route as AppGenerateEtsyRouteImport } from './routes/app/generate/etsy'
import { Route as AppGenerateBlogRouteImport } from './routes/app/generate/blog'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTiktokRoute = AppTiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppPackageRoute = AppPackageRouteImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => AppRoute,
} as any)
const AppNewProjectRoute = AppNewProjectRouteImport.update({
  id: '/new-project',
  path: '/new-project',
  getParentRoute: () => AppRoute,
} as any)
const AppImageStudioRoute = AppImageStudioRouteImport.update({
  id: '/image-studio',
  path: '/image-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppContentLibraryRoute = AppContentLibraryRouteImport.update({
  id: '/content-library',
  path: '/content-library',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandRoute = AppBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppBetaWelcomeRoute = AppBetaWelcomeRouteImport.update({
  id: '/beta-welcome',
  path: '/beta-welcome',
  getParentRoute: () => AppRoute,
} as any)
const AppBetaSignupsRoute = AppBetaSignupsRouteImport.update({
  id: '/beta-signups',
  path: '/beta-signups',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTrackingRoute = AppAdminTrackingRouteImport.update({
  id: '/admin-tracking',
  path: '/admin-tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppSignUpIndexRoute = AppSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AppRoute,
} as any)
const AppSignInIndexRoute = AppSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AppRoute,
} as any)
const AppSignUpSplatRoute = AppSignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => AppRoute,
} as any)
const AppSignInSplatRoute = AppSignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppGeneratePinterestRoute = AppGeneratePinterestRouteImport.update({
  id: '/generate/pinterest',
  path: '/generate/pinterest',
  getParentRoute: () => AppRoute,
} as any)
const AppGenerateEtsyRoute = AppGenerateEtsyRouteImport.update({
  id: '/generate/etsy',
  path: '/generate/etsy',
  getParentRoute: () => AppRoute,
} as any)
const AppGenerateBlogRoute = AppGenerateBlogRouteImport.update({
  id: '/generate/blog',
  path: '/generate/blog',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin-tracking': typeof AppAdminTrackingRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/beta-signups': typeof AppBetaSignupsRoute
  '/app/beta-welcome': typeof AppBetaWelcomeRoute
  '/app/billing': typeof AppBillingRoute
  '/app/brand': typeof AppBrandRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/content-library': typeof AppContentLibraryRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/image-studio': typeof AppImageStudioRoute
  '/app/new-project': typeof AppNewProjectRoute
  '/app/package': typeof AppPackageRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tiktok': typeof AppTiktokRoute
  '/app/': typeof AppIndexRoute
  '/app/generate/blog': typeof AppGenerateBlogRoute
  '/app/generate/etsy': typeof AppGenerateEtsyRoute
  '/app/generate/pinterest': typeof AppGeneratePinterestRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/sign-in/$': typeof AppSignInSplatRoute
  '/app/sign-up/$': typeof AppSignUpSplatRoute
  '/app/sign-in/': typeof AppSignInIndexRoute
  '/app/sign-up/': typeof AppSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/admin-tracking': typeof AppAdminTrackingRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/beta-signups': typeof AppBetaSignupsRoute
  '/app/beta-welcome': typeof AppBetaWelcomeRoute
  '/app/billing': typeof AppBillingRoute
  '/app/brand': typeof AppBrandRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/content-library': typeof AppContentLibraryRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/image-studio': typeof AppImageStudioRoute
  '/app/new-project': typeof AppNewProjectRoute
  '/app/package': typeof AppPackageRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tiktok': typeof AppTiktokRoute
  '/app': typeof AppIndexRoute
  '/app/generate/blog': typeof AppGenerateBlogRoute
  '/app/generate/etsy': typeof AppGenerateEtsyRoute
  '/app/generate/pinterest': typeof AppGeneratePinterestRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/sign-in/$': typeof AppSignInSplatRoute
  '/app/sign-up/$': typeof AppSignUpSplatRoute
  '/app/sign-in': typeof AppSignInIndexRoute
  '/app/sign-up': typeof AppSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin-tracking': typeof AppAdminTrackingRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/beta-signups': typeof AppBetaSignupsRoute
  '/app/beta-welcome': typeof AppBetaWelcomeRoute
  '/app/billing': typeof AppBillingRoute
  '/app/brand': typeof AppBrandRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/content-library': typeof AppContentLibraryRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/image-studio': typeof AppImageStudioRoute
  '/app/new-project': typeof AppNewProjectRoute
  '/app/package': typeof AppPackageRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tiktok': typeof AppTiktokRoute
  '/app/': typeof AppIndexRoute
  '/app/generate/blog': typeof AppGenerateBlogRoute
  '/app/generate/etsy': typeof AppGenerateEtsyRoute
  '/app/generate/pinterest': typeof AppGeneratePinterestRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/sign-in/$': typeof AppSignInSplatRoute
  '/app/sign-up/$': typeof AppSignUpSplatRoute
  '/app/sign-in/': typeof AppSignInIndexRoute
  '/app/sign-up/': typeof AppSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/admin-tracking'
    | '/app/analytics'
    | '/app/beta-signups'
    | '/app/beta-welcome'
    | '/app/billing'
    | '/app/brand'
    | '/app/calendar'
    | '/app/content-library'
    | '/app/feedback'
    | '/app/image-studio'
    | '/app/new-project'
    | '/app/package'
    | '/app/performance'
    | '/app/pricing'
    | '/app/settings'
    | '/app/tiktok'
    | '/app/'
    | '/app/generate/blog'
    | '/app/generate/etsy'
    | '/app/generate/pinterest'
    | '/app/projects/$projectId'
    | '/app/sign-in/$'
    | '/app/sign-up/$'
    | '/app/sign-in/'
    | '/app/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/admin-tracking'
    | '/app/analytics'
    | '/app/beta-signups'
    | '/app/beta-welcome'
    | '/app/billing'
    | '/app/brand'
    | '/app/calendar'
    | '/app/content-library'
    | '/app/feedback'
    | '/app/image-studio'
    | '/app/new-project'
    | '/app/package'
    | '/app/performance'
    | '/app/pricing'
    | '/app/settings'
    | '/app/tiktok'
    | '/app'
    | '/app/generate/blog'
    | '/app/generate/etsy'
    | '/app/generate/pinterest'
    | '/app/projects/$projectId'
    | '/app/sign-in/$'
    | '/app/sign-up/$'
    | '/app/sign-in'
    | '/app/sign-up'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/admin-tracking'
    | '/app/analytics'
    | '/app/beta-signups'
    | '/app/beta-welcome'
    | '/app/billing'
    | '/app/brand'
    | '/app/calendar'
    | '/app/content-library'
    | '/app/feedback'
    | '/app/image-studio'
    | '/app/new-project'
    | '/app/package'
    | '/app/performance'
    | '/app/pricing'
    | '/app/settings'
    | '/app/tiktok'
    | '/app/'
    | '/app/generate/blog'
    | '/app/generate/etsy'
    | '/app/generate/pinterest'
    | '/app/projects/$projectId'
    | '/app/sign-in/$'
    | '/app/sign-up/$'
    | '/app/sign-in/'
    | '/app/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tiktok': {
      id: '/app/tiktok'
      path: '/tiktok'
      fullPath: '/app/tiktok'
      preLoaderRoute: typeof AppTiktokRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pricing': {
      id: '/app/pricing'
      path: '/pricing'
      fullPath: '/app/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/package': {
      id: '/app/package'
      path: '/package'
      fullPath: '/app/package'
      preLoaderRoute: typeof AppPackageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new-project': {
      id: '/app/new-project'
      path: '/new-project'
      fullPath: '/app/new-project'
      preLoaderRoute: typeof AppNewProjectRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/image-studio': {
      id: '/app/image-studio'
      path: '/image-studio'
      fullPath: '/app/image-studio'
      preLoaderRoute: typeof AppImageStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feedback': {
      id: '/app/feedback'
      path: '/feedback'
      fullPath: '/app/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/content-library': {
      id: '/app/content-library'
      path: '/content-library'
      fullPath: '/app/content-library'
      preLoaderRoute: typeof AppContentLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/brand': {
      id: '/app/brand'
      path: '/brand'
      fullPath: '/app/brand'
      preLoaderRoute: typeof AppBrandRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/beta-welcome': {
      id: '/app/beta-welcome'
      path: '/beta-welcome'
      fullPath: '/app/beta-welcome'
      preLoaderRoute: typeof AppBetaWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/beta-signups': {
      id: '/app/beta-signups'
      path: '/beta-signups'
      fullPath: '/app/beta-signups'
      preLoaderRoute: typeof AppBetaSignupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin-tracking': {
      id: '/app/admin-tracking'
      path: '/admin-tracking'
      fullPath: '/app/admin-tracking'
      preLoaderRoute: typeof AppAdminTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sign-up/': {
      id: '/app/sign-up/'
      path: '/sign-up'
      fullPath: '/app/sign-up/'
      preLoaderRoute: typeof AppSignUpIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sign-in/': {
      id: '/app/sign-in/'
      path: '/sign-in'
      fullPath: '/app/sign-in/'
      preLoaderRoute: typeof AppSignInIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sign-up/$': {
      id: '/app/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/app/sign-up/$'
      preLoaderRoute: typeof AppSignUpSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sign-in/$': {
      id: '/app/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/app/sign-in/$'
      preLoaderRoute: typeof AppSignInSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/generate/pinterest': {
      id: '/app/generate/pinterest'
      path: '/generate/pinterest'
      fullPath: '/app/generate/pinterest'
      preLoaderRoute: typeof AppGeneratePinterestRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/generate/etsy': {
      id: '/app/generate/etsy'
      path: '/generate/etsy'
      fullPath: '/app/generate/etsy'
      preLoaderRoute: typeof AppGenerateEtsyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/generate/blog': {
      id: '/app/generate/blog'
      path: '/generate/blog'
      fullPath: '/app/generate/blog'
      preLoaderRoute: typeof AppGenerateBlogRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminTrackingRoute: typeof AppAdminTrackingRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBetaSignupsRoute: typeof AppBetaSignupsRoute
  AppBetaWelcomeRoute: typeof AppBetaWelcomeRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBrandRoute: typeof AppBrandRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppContentLibraryRoute: typeof AppContentLibraryRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppImageStudioRoute: typeof AppImageStudioRoute
  AppNewProjectRoute: typeof AppNewProjectRoute
  AppPackageRoute: typeof AppPackageRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppPricingRoute: typeof AppPricingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTiktokRoute: typeof AppTiktokRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGenerateBlogRoute: typeof AppGenerateBlogRoute
  AppGenerateEtsyRoute: typeof AppGenerateEtsyRoute
  AppGeneratePinterestRoute: typeof AppGeneratePinterestRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppSignInSplatRoute: typeof AppSignInSplatRoute
  AppSignUpSplatRoute: typeof AppSignUpSplatRoute
  AppSignInIndexRoute: typeof AppSignInIndexRoute
  AppSignUpIndexRoute: typeof AppSignUpIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminTrackingRoute: AppAdminTrackingRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBetaSignupsRoute: AppBetaSignupsRoute,
  AppBetaWelcomeRoute: AppBetaWelcomeRoute,
  AppBillingRoute: AppBillingRoute,
  AppBrandRoute: AppBrandRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppContentLibraryRoute: AppContentLibraryRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppImageStudioRoute: AppImageStudioRoute,
  AppNewProjectRoute: AppNewProjectRoute,
  AppPackageRoute: AppPackageRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppPricingRoute: AppPricingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTiktokRoute: AppTiktokRoute,
  AppIndexRoute: AppIndexRoute,
  AppGenerateBlogRoute: AppGenerateBlogRoute,
  AppGenerateEtsyRoute: AppGenerateEtsyRoute,
  AppGeneratePinterestRoute: AppGeneratePinterestRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppSignInSplatRoute: AppSignInSplatRoute,
  AppSignUpSplatRoute: AppSignUpSplatRoute,
  AppSignInIndexRoute: AppSignInIndexRoute,
  AppSignUpIndexRoute: AppSignUpIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
